exclude_patterns:
- "bin/"
- "config/"
- "coverage/"
- "db/"
- "dist/"
- "features/"
- "lib/"
- "log/"
- "**/node_modules/"
- "public/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "Tests/"
- "tmp/"
- "**/vendor/"
- "**/*_test.go"
- "**/*.d.ts"
- "babel.config.js"
