# Any 32 characters would do. Currently it's just for testing.
attr_encrypted_key: "12345678912345678912345678912345"
# Email password for SES
email_password: "BPeP7G25Yg5XBYjZK5N1R4eXvT3PZcXfO2VC2Njkxpdk"

GOOGLE_CLIENT_ID: "721984503543-0na9frni8n9600lhtpgpo9v998ha1ej9.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET: "TJheFmX35CrVc1BJHhZnrdKa"
LANG: "en_US.UTF-8"
PORT: "3000"
RACK_ENV: "development"
RAILS_ENV: "development"
RAILS_SERVE_STATIC_FILES: "true"
SECRET_KEY_BASE: "6952b19932b43c62e7db551f7c9f7959ea72792bcf443609c4a1cbc3b01368ae"
teacher_key: "784390af75de89" # not sure what this is used for.
ADMIN_EMAILS: "longhtong@berkeley.edu, tony@stark.com"
SENTRY_DSN: "https://19d6d747d49d4a99a03764dbeaf73e82:a933d558ddcc42d2abf11161655e8f4f@sentry.cs10.org/4" 