name: build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CCTR: ./cc-test-reporter
      BUNDLE_WITHOUT: production
      
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.17.0'
    - name: Use Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.5
        bundler-cache: true
    - run: bin/yarn
    - run: bin/rails webpacker:compile
    - run: bundle exec rake db:setup
    - run: bundle exec rake db:migrate
        
    - name: Setup CodeClimate test-reporter
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > $CCTR
        chmod +x $CCTR
        $CCTR before-build

    - name: run RSpec tests and capture coverage
      run: |
        bundle exec rspec
        $CCTR format-coverage --output coverage/codeclimate.$SUITE.json --input-type simplecov
        
    - name: run Cucumber tests and capture coverage
      run: |
        bundle exec cucumber --retry 2
        $CCTR format-coverage --output coverage/codeclimate.$SUITE.json --input-type simplecov
  
    - name: Publish code coverage
      run: |
        export GIT_BRANCH="${GITHUB_REF/refs\/heads\//}"
        $CCTR sum-coverage coverage/codeclimate.*.json
        $CCTR upload-coverage --id ${{ secrets.CC_TEST_REPORTER_ID }}
        $CCTR after-build --id ${{ secrets.CC_TEST_REPORTER_ID }}