name: All Specs

on: [push, pull_request]

jobs:
  specs:
    name: Tests
    runs-on: ubuntu-latest
    continue-on-error: true
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
    strategy:
      fail-fast: false
      matrix:
        suite:
          - cucumber
          - rspec
    env:
      TZ: America/Los_Angeles
      RAILS_ENV: test
      RUBY_ENV: test
      attr_encrypted_key: '12345678912345678912345678912345'
      DISPLAY: ':99' # For chromedriver
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Use Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.5
          bundler-cache: true
      - name: Setup Code Climate
        run: |
            export GIT_BRANCH="${GITHUB_REF/refs\/heads\//}"
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reportere
      - run: bin/yarn
      - run: bin/rails webpacker:compile
      - run: bundle exec rake db:setup
      - run: bundle exec rake db:migrate
      - run: bundle exec ${{ matrix.suite }}
      - name: CodeCov Coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Publish Code Climate
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          ./cc-test-reporter format-coverage -t simplecov coverage/coverage.xml
          ./cc-test-reporter upload-coverage
      # - name: Code Climate coveragem
      #   uses: paambaati/codeclimate-action@v3.0.0
      #   env:
      #     CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      #   with:
      #     coverageLocations: simplecov
      #     debug: true
